development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: KT86mn_!
  database: postgres
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: KT86mn_!
  database: postgres        
  encoding: UTF8